<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit341dcda3274fcd4a2f24f156797923fc
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Raven_' => 
            array (
                0 => __DIR__ . '/..' . '/sentry/sentry/lib',
            ),
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 
            array (
                0 => __DIR__ . '/..' . '/psr/log',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit341dcda3274fcd4a2f24f156797923fc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit341dcda3274fcd4a2f24f156797923fc::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit341dcda3274fcd4a2f24f156797923fc::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
